specify counts columns in manual_drops
jbloomlab/seqneut-pipeline pull request #46
Opened 2024-04-23 22:36 UTC by ckikawa

This pull request should resolve #45 by adding additional `elif` statements to a cell of `process_plate.ipynb` where manual_drops are removed from the `counts` dataframe. I tested this with multiple `wells` on some recent H3N2 `ngs-neut` data. 

As is, single wells/barcodes cannot be specified in lists (as indicated in `README`). They must be added as individual lines with dashes. If this is expected behavior, ignore this comment. Otherwise, I can add this detail to `README`?

2024-04-23 23:25 UTC, anloes commented
I think we should add instructions to the README.md, if was not immediately obvious that this is what should be done, an
 example would work.

2024-04-23 23:31 UTC, jbloom requested changes
@ckikawa, can you just update this in the CHANGELOG too. As I understand it, this is just a bug fix so that can be a minor version (3.1.1) as no new functionality was added, it just makes something that already is supposed to happen work correctly.

Just briefly explain what is fixed and link to the issue, as in other CHANGELOG entries.

I don't quite understand @anloes's comment as I don't think anything needs to be added to README as this is just fixing a bug that prevented previously documented functionality from actually working correctly, right? Can you clarify that is correct with her?

2024-04-23 23:38 UTC, anloes commented
Yes, you are correct that this was a bug fix. However, there is not currently an example of how a single well or a barcode should be listed for exclusion. It was unclear if they should be in brackets around the entry or if these could just be listed as strings. I would recommend we update the README.md section on manual drops to show an example of each, i.e.:

manual_drops:
  barcode_serum_replicates:
    - [AGTCCTATCCTCAAAT, M099d0]
  wells:
    - A1

2024-04-23 23:41 UTC, jbloom commented
It should just be a list, which can be specified in either of two ways in YAML:
```
wells: [A1, A2]
```
or
```
wells:
  - A1
  - A2
```
It says this verbally in README, but you can add in example if you want @ckikawa

2024-04-23 23:47 UTC, ckikawa commented
@jbloom, I see. I think this was just a YAML formatting quirk that I wasn't familiar with. I was trying (and failing) with:
```
wells:
  - [A1, A2]
```

I've updated the CHANGELOG but I'm not sure an example in README is necessary.

2024-04-24 01:45 UTC, jbloom approved these changes

2024-04-24 01:45 UTC, merged